name: Global Package
on:
  push:
    branches:
      - '**'
jobs:
  todelete:
    timeout-minutes: 5
    runs-on: ubuntu-latest
  steps:

      - name: Use Node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install globally
        run: npm install typescript -g

      - name: Use the global package
        run: tsc --version
